trigger:
 - development

stages:
  - stage: Build
    jobs:
      - job: Build
    displayName: Build the web application
    pool:
     name: AzDevopsagent1
     demands:
      - mvn

     steps:
     - task: Maven@4
       inputs:
       mavenPomFile: 'pom.xml'
       testResultsFiles: '**surefire-reports/TEST-*.xml'
       javaHomeOption: JDKVersion
       mavenVersionOption: Default
     
     - task: CopyFiles@2
       inputs:
       Contents: '**/target/*.jar'
       TargetFolder: '$(Build.ArtifactStagingDirectory)'

     - task: PublishPipelineArtifact@1
       inputs:
       targetPath: '$(Pipeline.Workspace)'
       publishLocation: 'pipeline'
       artifact: 'drop' 

  - stage: 'dev'
    jobs:
    - deployment: deploy
      environment: dev
    displayName: 'Deploy to Dev environment'
    dependsOn: Build
    pool:
         name: AzDevopsagent1
         strategy:
         runOnce:
           deploy:
             steps:
               - download: current
                 artifact: drop

  - stage: 'test'
    jobs:
    - deployment: deploy
      environment: test
    displayName: Deploy to Test environment'
    dependsOn: Dev
    pool:
         name: AzDevopsagent1
         strategy:
         runOnce:
           deploy:
             steps:
               - download: current
                 artifact: drop

  - stage: 'staging'
    jobs:
    - deployment: deploy
      environment: staging
    displayName: Deploy to Test environment'
    dependsOn: test
    pool:
         name: AzDevopsagent1
         strategy:
         runOnce:
           deploy:
             steps:
               - download: current
                 artifact: drop
